name: newsly
description: Love Your news One Swipe at a time.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  flutter_card_swiper: ^6.0.0
  provider: ^6.0.5
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.6.0
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher_round.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/ic_launcher_round.png"
    background_color: "#hexcode"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/ic_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/ic_launcher_round.png"
