// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwGcHk5EYlsSAecmzdgULvfel_FYsB2Cg',
    appId: '1:853778555024:android:bf7e26144342719066f815',
    messagingSenderId: '853778555024',
    projectId: 'newsly-app-1764-test',
    storageBucket: 'newsly-app-1764-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6CffFGk6PHy_uN-cmBNRwcg8OxeB4hY',
    appId: '1:853778555024:ios:a4bd9cd93339335f66f815',
    messagingSenderId: '853778555024',
    projectId: 'newsly-app-1764-test',
    storageBucket: 'newsly-app-1764-test.appspot.com',
    androidClientId: '853778555024-949r1kqipiq4q1kp15e55o2c0l5k5idq.apps.googleusercontent.com',
    iosClientId: '853778555024-ddnsa532mlqd5k9nhngnpv0fo2j9clre.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsly.newsly',
  );
}
